const express = require('express')
const orderRouter = express.Router()
const orderHandler = require('../routerHandler/ordersHandler')
orderRouter.get('/getOrders', orderHandler.getOrders)
orderRouter.post('/addOrders', orderHandler.addOrders)
orderRouter.post('/deleteOrder', orderHandler.deleteOrders)
orderRouter.post('/searchOrders', orderHandler.searchOrders)
orderRouter.post('/doneOrder', orderHandler.doneOrders)
orderRouter.post('/settleOrder', orderHandler.settleOrder)
orderRouter.post('/getPaidResult', orderHandler.queryPaidStatus)
orderRouter.get('/listenOrders', orderHandler.listenOrders)
module.exports = orderRouter